apiVersion: v1

kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:
  MONGO_URI: "mongodb://mongodb-service:27017/saree-store"
  JWT_SECRET: "your_super_secret_jwt_key_change_in_production_min_32_chars"

  CLOUDINARY_CLOUD_NAME: "dbvpxcdso"
  CLOUDINARY_API_KEY: "547757451292692"
  CLOUDINARY_API_SECRET: "VTFaeqDvjtA2Dka0Eo4h7NBAh7s"

  EASEBUZZ_KEY: "M8YLX5X9Q"
  EASEBUZZ_SALT: "07JHRA9CQ"

  STRIPE_SECRET_KEY: "sk_test_your_stripe_secret_key"

  SMTP_EMAIL: "tanveerchauhan604@gmail.com"
  SMTP_PASSWORD: "lmnw ifhj udmg roqj"
